apiVersion: v1
kind: PersistentVolume
metadata:
  name: n8n-pv
  namespace: n8n
spec:
  capacity:
    storage: 500Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/n8n"
