apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
      - name: n8n
        image: n8nio/n8n:1.112.1
        ports:
        - containerPort: 5678
        env:
        - name: DB_TYPE
          value: postgres
        - name: DB_POSTGRESDB_HOST
          value: postgres
        - name: DB_POSTGRESDB_PORT
          value: "5432"
        - name: DB_POSTGRESDB_DATABASE
          value: n8n
        - name: DB_POSTGRESDB_USER
          value: n8n
        - name: DB_POSTGRESDB_PASSWORD
          value: n8npass
        - name: GENERIC_TIMEZONE
          value: Asia/Singapore
        - name: N8N_HOST
          value: 0.0.0.0
        - name: N8N_PORT
          value: "5678"
        - name: WEBHOOK_TUNNEL_URL
          value: "http://<node-ip>:30080"
        - name: N8N_SECURE_COOKIE
          value: "false"
        volumeMounts:
        - mountPath: /home/node/.n8n
          name: n8n-storage
      volumes:
      - name: n8n-storage
        persistentVolumeClaim:
          claimName: n8n-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: n8n-service
  namespace: n8n
spec:
  type: NodePort
  selector:
    app: n8n
  ports:
  - port: 80
    targetPort: 5678
    nodePort: 30080